name: Main CD Pipeline

on:
# Testing on dev branch
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ dev ]

jobs:
  backend-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build Project
        env:
          AWS_DB_USER: ${{ secrets.AWS_DB_USER }}
          AWS_DB_PASS: ${{ secrets.AWS_DB_PASS }}
        run: mvn clean install -DskipTests

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DH_USER }} -p ${{ secrets.DH_PASS }}
      - name: Build docker image
        run: docker build -t maverickgdn01/artifactup .
      - name: Publish image to docker hub
        run: docker push maverickgdn01/artifactup:latest


  deploy:
    needs: backend-build
    runs-on: [aws-ec2-backend]
    steps:
      - name: Verify Docker Installation
        run: docker --version
      - name: Pull Image from Docker Hub
        run: docker pull maverickgdn01/artifactup:latest
      - name: Delete Existing Container
        run: docker rm -f artifactup
      - name: Run Docker Container
        run: docker run -d -p 8080:8080 --name artifactup maverickgdn01/artifactup:latest
